#!/bin/bash


configfile="${chrootdir}/etc/rbackup.conf"

if ! [[ -f "${configfile}" ]]; then
    cp example_backup.conf "${configfile}"
fi

scriptname="rbackup"
pullname="pull"
pushname="push"

(
    IFS=:
    for p in $PATH; do
        if [[ -f "${p%/}/${pullname}" ]]; then
            echo "Name conflict in PATH with ${p}/${pullname}. Exiting."
            exit 1
        elif [[ -f "${p%/}/${pushname}" ]]; then
            echo "Name conflict in PATH with ${p}/${pushname}. Exiting."
            exit 1
        fi
    done
)

installdir="${chrootdir}/bin"

if ! [[ -d "${installdir}" ]]; then
    mkdir -p "${installdir}"
else
    if [[ -f "${installdir}/${pullname}" ]]; then
        echo "Name conflict in install dir with ${installdir}/${pullname}. Exiting."
        exit 1
    elif [[ -f "${installdir}/${pushname}" ]]; then
        echo "Name conflict in install dir with ${installdir}/${pushname}. Exiting."
        exit 1
    fi
fi

cp "${scriptname}" "${installdir}/${pullname}"
chmod 775 "${installdir}/${pullname}"
cp "${scriptname}" "${installdir}/${pushname}"
chmod 775 "${installdir}/${pushname}"

echo "Done."
exit 0
