#!/bin/bash

DELETE="--delete"
POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    -m|--merge)
      DELETE=""
      shift # past argument
#      shift # past value
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

rsync -aAXuv $DELETE ${POSITIONAL_ARGS[@]} koyo@oniisan.hopto.org:rsync/doc/ ~/doc
